app:
  authBypassed: false
writeDatabase:
  driverClass: software.aws.rds.jdbc.mysql.Driver
  url: jdbc:mysql:aws://${DB_RO_SHOP_HOST}/${DB_NA_SHOP_NAME}?zeroDateTimeBehavior=CONVERT_TO_NULL
  user: ${DB_RO_SHOP_USERNAME}
  password: ${DB_RO_SHOP_PASSWORD}

  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  checkConnectionOnBorrow: true

server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
      useServerHeader: false
      useDateHeader: false
      useForwardedHeaders: false
      maxRequestHeaderSize: 16KiB
  adminConnectors:
    - type: http
      port: 8081
      acceptorThreads: 1
      selectorThreads: 1
  requestLog:
    appenders: []