/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fabfitfun.hackathon.avro.customersegmentation;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserProductInterest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2405189234137060556L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserProductInterest\",\"namespace\":\"com.fabfitfun.hackathon.avro.customersegmentation\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"keyword\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserProductInterest> ENCODER =
      new BinaryMessageEncoder<UserProductInterest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserProductInterest> DECODER =
      new BinaryMessageDecoder<UserProductInterest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserProductInterest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserProductInterest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserProductInterest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserProductInterest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserProductInterest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserProductInterest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserProductInterest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserProductInterest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long userId;
   private java.lang.String keyword;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserProductInterest() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param keyword The new value for keyword
   */
  public UserProductInterest(java.lang.Long userId, java.lang.String keyword) {
    this.userId = userId;
    this.keyword = keyword;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return keyword;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: keyword = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'keyword' field.
   * @return The value of the 'keyword' field.
   */
  public java.lang.String getKeyword() {
    return keyword;
  }


  /**
   * Sets the value of the 'keyword' field.
   * @param value the value to set.
   */
  public void setKeyword(java.lang.String value) {
    this.keyword = value;
  }

  /**
   * Creates a new UserProductInterest RecordBuilder.
   * @return A new UserProductInterest RecordBuilder
   */
  public static com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder newBuilder() {
    return new com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder();
  }

  /**
   * Creates a new UserProductInterest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserProductInterest RecordBuilder
   */
  public static com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder newBuilder(com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder other) {
    if (other == null) {
      return new com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder();
    } else {
      return new com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder(other);
    }
  }

  /**
   * Creates a new UserProductInterest RecordBuilder by copying an existing UserProductInterest instance.
   * @param other The existing instance to copy.
   * @return A new UserProductInterest RecordBuilder
   */
  public static com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder newBuilder(com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest other) {
    if (other == null) {
      return new com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder();
    } else {
      return new com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserProductInterest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserProductInterest>
    implements org.apache.avro.data.RecordBuilder<UserProductInterest> {

    private long userId;
    private java.lang.String keyword;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.keyword)) {
        this.keyword = data().deepCopy(fields()[1].schema(), other.keyword);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing UserProductInterest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.keyword)) {
        this.keyword = data().deepCopy(fields()[1].schema(), other.keyword);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'keyword' field.
      * @return The value.
      */
    public java.lang.String getKeyword() {
      return keyword;
    }


    /**
      * Sets the value of the 'keyword' field.
      * @param value The value of 'keyword'.
      * @return This builder.
      */
    public com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder setKeyword(java.lang.String value) {
      validate(fields()[1], value);
      this.keyword = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'keyword' field has been set.
      * @return True if the 'keyword' field has been set, false otherwise.
      */
    public boolean hasKeyword() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'keyword' field.
      * @return This builder.
      */
    public com.fabfitfun.hackathon.avro.customersegmentation.UserProductInterest.Builder clearKeyword() {
      keyword = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserProductInterest build() {
      try {
        UserProductInterest record = new UserProductInterest();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.keyword = fieldSetFlags()[1] ? this.keyword : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserProductInterest>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserProductInterest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserProductInterest>
    READER$ = (org.apache.avro.io.DatumReader<UserProductInterest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.userId);

    out.writeString(this.keyword);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readLong();

      this.keyword = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readLong();
          break;

        case 1:
          this.keyword = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










