app:
  authBypassed: false
writeDatabase:
  driverClass: software.aws.rds.jdbc.mysql.Driver
  url: jdbc:mysql://rds-dev-shop-cluster.cluster-c1yqzlng7npm.us-west-2.rds.amazonaws.com/ssoblog?zeroDateTimeBehavior=convertToNull&useSSL=false
  user: dev
  password: {password}

  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  checkConnectionOnBorrow: true

server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
      useServerHeader: false
      useDateHeader: false
      useForwardedHeaders: false
      maxRequestHeaderSize: 16KiB
  adminConnectors:
    - type: http
      port: 8081
      acceptorThreads: 1
      selectorThreads: 1
  requestLog:
    appenders: []